interface SpatialReference {
    wkid: number;
}

export interface Polygon {
    rings: number[][][];
    spatialReference: SpatialReference;
}

export interface Aoi {
    description: string;
    polygon: Polygon;
}

export interface HazardInfo {
    url: string;
    hazard: string;
    units: string[];
}


export interface Task {
    [key: string]: boolean;
}

export interface HazardUnit {
    HazardName: string;
    HowToUse: string;
    Description: string;
    HazardUnit: string;
    UnitName: string;
}

export interface HazardIntro {
    Hazard: string;
    Text: string;
}

export interface HazardReference {
    Hazard: string;
    Text: string;
}

export interface HazardToUnitMapType {
    [key: string]: HazardUnit[];
}

export interface ReportTextMapType {
    Bottom: string;
    Disclaimer: string;
    Introduction: string;
    OtherGeologicalHazardResources: string;
    ['Table1headingautogenerated table']: string;
    ['Table2headingautogenerated table']: string;
    ['Table3headingautogenerated table']: string;
    ['Table4headingautogenerated table']: string;
    Top: string;
}
